name: Build All and Upload Artifacts

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout the current branch.
        uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
      - name: Setup Node.js - 12.x.x
        uses: actions/setup-node@b6651e20e530d6e6b845a9828606779e89f5529c
        with:
          node-version: '>=12.10'
      - name: Install project dependencies.
        run: npm install
      - name: Check for Lint issues.
        run: npm run lint
      - name: Build the test Electron app.
        run: |
          npm run test-build
          npm run test-dist
      - name: Build the test Web app.
        run: npm run test-build-web
      - name: Run all tests
        run: npm run test
      - name: Build the Electron project.
        run: npm run build
      - name: Build the Web project.
        run: npm run build-web
      - name: Build artifacts for all supported OSes.
        run: npm run dist-all
      - name: Delete useless artifacts.
        run: node bin/remove_unneeded_artifacts.js
      - name: Upload artifacts.
        uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5
        with:
          name: artifacts
          path: dist/electron-app
