name: Production Releases
on:
  push:
    tags:
      - "v*"
jobs:
  assert-no-issues:
    name: "Assert no issues"
    runs-on: macos-latest
    steps:
      - name: Checkout the current branch.
        uses: actions/checkout@v2
      - name: Setup Node.js - 12.x.x
        uses: actions/setup-node@v1
        with:
          node-version: '>=12.10'
      - name: Install project dependencies.
        run: npm ci
      - name: Check for Lint issues.
        run: npm run lint
      - name: Build the test Electron app.
        run: |
          npm run build-test-app
          npm run dist-test-app
      - name: Build the test Web app.
        run: npm run build-test-web
      - name: Run all tests
        run: npm run test
  deploy-web:
    needs: assert-no-issues
    name: "Deploy Web"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current branch.
        uses: actions/checkout@v2
      - name: Setup Node.js - 12.x.x
        uses: actions/setup-node@v1
        with:
          node-version: '>=12.10'
      - name: Install project dependencies.
        run: npm ci
      - name: Build Web.
        run: npm run build-web
      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.LYRICISTANT_TOKEN }}
          external_repository: wardellbagby/lyricistant-website
          publish_branch: gh-pages
          publish_dir: dist/web
          force_orphan: true
          cname: lyricistant.app
  deploy-app:
    needs: assert-no-issues
    name: "Deploy App"
    runs-on: macos-latest
    steps:
      - name: Checkout the current branch.
        uses: actions/checkout@v2
      - name: Setup Node.js - 12.x.x
        uses: actions/setup-node@v1
        with:
          node-version: '>=12.10'
      - name: Install project dependencies.
        run: npm ci
      - name: Build the Electron project.
        run: npm run build-app
      - name: Build artifacts for all supported OSes.
        run: npm run dist-all-apps
      - name: Delete useless artifacts.
        run: node bin/remove_unneeded_artifacts.js
      - name: "Deploy App"
        uses: "marvinpinto/action-automatic-releases@v1.1.0"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: dist/electron-app/*.*